# Generated by Django 2.1.4 on 2021-09-27 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Link',
            new_name='Todo',
        ),
    ]
