# Generated by Django 2.1.4 on 2021-09-27 06:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210927_0450'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='createdOn',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo',
            name='open',
            field=models.BooleanField(default=True),
        ),
    ]
